const categories = [
  {
    id: "cat1",
    name: "Headphones",
    emoji: "🎧",
    imageUrl: "",
    slug: "headphones",
  },
  {
    id: "cat2",
    name: "Smart Watches",
    emoji: "⌚",
    imageUrl: "https://img.cdndsgni.com/preview/10598518.jpg",
    slug: "smart-watches",
  },
  {
    id: "cat3",
    name: "Speakers",
    emoji: "🔊",
    imageUrl: "",
    slug: "speakers",
  },
  {
    id: "cat4",
    name: "Accessories",
    emoji: "🔌",
    imageUrl: "",
    slug: "accessories",
  },
  {
    id: "cat5",
    name: "Laptops",
    emoji: "💻",
    imageUrl: "",
    slug: "laptops",
  },
  {
    id: "cat6",
    name: "Smartphones",
    emoji: "📱",
    imageUrl: "",
    slug: "smartphones",
  },
  {
    id: "cat7",
    name: "Gaming Consoles",
    emoji: "🎮",
    imageUrl: "",
    slug: "gaming-consoles",
  },
  {
    id: "cat8",
    name: "Cameras",
    emoji: "📷",
    imageUrl: "",
    slug: "cameras",
  },
  {
    id: "cat9",
    name: "Tablets",
    emoji: "📝",
    imageUrl: "",
    slug: "tablets",
  },
  {
    id: "cat10",
    name: "Drones",
    emoji: "🛸",
    imageUrl: "",
    slug: "drones",
  },
  {
    id: "cat11",
    name: "Chargers",
    emoji: "🔋",
    imageUrl: "",
    slug: "chargers",
  },
  {
    id: "cat12",
    name: "Monitors",
    emoji: "🖥️",
    imageUrl: "",
    slug: "monitors",
  },
  {
    id: "cat13",
    name: "Keyboards",
    emoji: "⌨️",
    imageUrl: "",
    slug: "keyboards",
  },
  {
    id: "cat14",
    name: "VR Headsets",
    emoji: "🕶️",
    imageUrl: "",
    slug: "vr-headsets",
  },
];

export default categories;
